const translations = {
  // TÜRKÇE
  tr: {
    settings: "AYARLAR",
    achievements: "BAŞARIMLAR",
    guide: "REHBER",
    sound_status: "Ses Durumu",
    night_day: "GECE / GÜNDÜZ",
    how_to_play: "NASIL OYNANIR?",
    reset: "SIFIRLA",
    start_game: "OYUNA BAŞLA",
    username_placeholder: "İsmini Yaz...",
    guide_text:
      "Toprağa tıkla, tohumları büyüt. Space tuşuna basılı tutarak seri tıklayabilirsin!",
    level_label: "SEVİYE",
    size_label: "Boyut:",
    target_label: "Hedef:",
    total_earnings: "TOPLAM KAZANÇ",
    total_clicks: "TOPLAM TIK",
    market_title: "MARKET",
    prestige_title: "PRESTİJ",
    prestige_desc: "Boyut Atla",
    prestige_power: "%50 GÜÇ",
    upg_click: "Güneş Işığı",
    upg_water: "Can Suyu",
    upg_auto: "Doğal Gübre",
    upg_shears: "Budama",
    upg_gloves: "Eldiven",
    upg_med: "Vitamin",
    upg_boost: "Uğur Böceği",
    bonus_click: "+1 Tık",
    bonus_water: "+2 Tık",
    bonus_auto: "+1.0 Oto",
    bonus_shears: "+5.0 Oto",
    bonus_gloves: "+10 Tık",
    bonus_med: "+25.0 Oto",
    bonus_boost: "Hız x2 (60sn)",
    welcome: "Hoş Geldin",
    good_luck: "Bol şans!",
    insufficient_sp: "Yetersiz SP",
    collect_points: "Puan biriktir.",
    level_up: "BOYUT ATLADIN!",
    new_dimension: "Yeni Boyut:",
    rebirth: "YENİDEN DOĞUŞ",
    stronger: "Daha güçlüsün!",
    golden_seed: "ALTIN TOHUM",
    bee: "ARI",
    offline_earnings: "ÇEVRİMDIŞI KAZANÇ",
    stage_0: "TOHUM",
    stage_1: "MİNİK FİLİZ",
    stage_2: "YEŞEREN FİDAN",
    stage_3: "GENÇ AĞAÇ",
    stage_4: "GÜÇLÜ GÖVDE",
    stage_5: "ÇİÇEKLİ AĞAÇ",
    stage_6: "MEYVE VEREN",
    stage_7: "ORMAN BEKÇİSİ",
    stage_8: "ULU ÇINAR",
    stage_9: "KADİM MEŞE",
    stage_10: "DOĞA RUHU",
    stage_11: "HAYAT AĞACI",
    stage_12: "GÖKYÜZÜ SÜTUNU",
    stage_13: "YILDIZ TOHUMU",
    stage_14: "EVRENİN NEFESİ",
    ach_1_title: "İlk Adım",
    ach_1_desc: "1 kere tıkla",
    ach_2_title: "Çalışkan Çiftçi",
    ach_2_desc: "500 kere tıkla",
    ach_3_title: "Otomasyon",
    ach_3_desc: "Gübre seviyesi 5 yap",
    ach_4_title: "Zengin",
    ach_4_desc: "10.000 SP biriktir",
    ach_5_title: "Boyut Gezgini",
    ach_5_desc: "2. Boyuta geç",
  },
  // İNGİLİZCE
  en: {
    settings: "SETTINGS",
    achievements: "ACHIEVEMENTS",
    guide: "GUIDE",
    sound_status: "Sound Status",
    night_day: "NIGHT / DAY",
    how_to_play: "HOW TO PLAY?",
    reset: "RESET DATA",
    start_game: "START GAME",
    username_placeholder: "Enter Name...",
    guide_text: "Click the soil, grow seeds. Hold Spacebar for rapid clicking!",
    level_label: "LEVEL",
    size_label: "Size:",
    target_label: "Target:",
    total_earnings: "TOTAL EARNINGS",
    total_clicks: "TOTAL CLICKS",
    market_title: "MARKET",
    prestige_title: "PRESTIGE",
    prestige_desc: "Dimension Up",
    prestige_power: "+50% POWER",
    upg_click: "Sunlight",
    upg_water: "Life Water",
    upg_auto: "Natural Fertilizer",
    upg_shears: "Pruning",
    upg_gloves: "Gloves",
    upg_med: "Vitamin",
    upg_boost: "Ladybug",
    bonus_click: "+1 Click",
    bonus_water: "+2 Click",
    bonus_auto: "+1.0 Auto",
    bonus_shears: "+5.0 Auto",
    bonus_gloves: "+10 Click",
    bonus_med: "+25.0 Auto",
    bonus_boost: "Speed x2 (60s)",
    welcome: "Welcome",
    good_luck: "Good Luck!",
    insufficient_sp: "Insufficient SP",
    collect_points: "Collect points.",
    level_up: "DIMENSION UP!",
    new_dimension: "New Dimension:",
    rebirth: "REBIRTH",
    stronger: "You are stronger!",
    golden_seed: "GOLDEN SEED",
    bee: "BEE",
    offline_earnings: "OFFLINE EARNINGS",
    stage_0: "SEED",
    stage_1: "TINY SPROUT",
    stage_2: "GROWING SAPLING",
    stage_3: "YOUNG TREE",
    stage_4: "STRONG TRUNK",
    stage_5: "FLOWERING TREE",
    stage_6: "FRUIT BEARING",
    stage_7: "FOREST GUARDIAN",
    stage_8: "GRAND PLANE",
    stage_9: "ANCIENT OAK",
    stage_10: "NATURE SPIRIT",
    stage_11: "TREE OF LIFE",
    stage_12: "SKY PILLAR",
    stage_13: "STAR SEED",
    stage_14: "BREATH OF UNIVERSE",
    ach_1_title: "First Step",
    ach_1_desc: "Click 1 time",
    ach_2_title: "Hard Worker",
    ach_2_desc: "Click 500 times",
    ach_3_title: "Automation",
    ach_3_desc: "Reach Fertilizer Lvl 5",
    ach_4_title: "Rich",
    ach_4_desc: "Collect 10.000 SP",
    ach_5_title: "Dimension Traveler",
    ach_5_desc: "Reach Dimension 2",
  },
  // İSPANYOLCA
  es: {
    settings: "AJUSTES",
    achievements: "LOGROS",
    guide: "GUÍA",
    sound_status: "Sonido",
    night_day: "NOCHE / DÍA",
    how_to_play: "¿CÓMO JUGAR?",
    reset: "REINICIAR",
    start_game: "EMPEZAR JUEGO",
    username_placeholder: "Tu Nombre...",
    guide_text:
      "Haz clic en la tierra, cultiva semillas. ¡Mantén Espacio para clics rápidos!",
    level_label: "NIVEL",
    size_label: "Tamaño:",
    target_label: "Meta:",
    total_earnings: "GANANCIAS TOTALES",
    total_clicks: "CLICS TOTALES",
    market_title: "MERCADO",
    prestige_title: "PRESTIGIO",
    prestige_desc: "Subir Dimensión",
    prestige_power: "+50% PODER",
    upg_click: "Luz Solar",
    upg_water: "Agua de Vida",
    upg_auto: "Fertilizante",
    upg_shears: "Poda",
    upg_gloves: "Guantes",
    upg_med: "Vitamina",
    upg_boost: "Mariquita",
    bonus_click: "+1 Clic",
    bonus_water: "+2 Clic",
    bonus_auto: "+1.0 Auto",
    bonus_shears: "+5.0 Auto",
    bonus_gloves: "+10 Clic",
    bonus_med: "+25.0 Auto",
    bonus_boost: "Vel. x2 (60s)",
    welcome: "Bienvenido",
    good_luck: "¡Buena suerte!",
    insufficient_sp: "SP Insuficiente",
    collect_points: "Consigue puntos.",
    level_up: "¡DIMENSIÓN ARRIBA!",
    new_dimension: "Nueva Dimensión:",
    rebirth: "RENACIMIENTO",
    stronger: "¡Eres más fuerte!",
    golden_seed: "SEMILLA DORADA",
    bee: "ABEJA",
    offline_earnings: "GANANCIAS OFFLINE",
    stage_0: "SEMILLA",
    stage_1: "BROTE PEQUEÑO",
    stage_2: "PLANTÓN",
    stage_3: "ÁRBOL JOVEN",
    stage_4: "TRONCO FUERTE",
    stage_5: "ÁRBOL EN FLOR",
    stage_6: "FRUTAL",
    stage_7: "GUARDIÁN BOSQUE",
    stage_8: "GRAN PLÁTANO",
    stage_9: "ROBLE ANTIGUO",
    stage_10: "ESPÍRITU NATURA",
    stage_11: "ÁRBOL DE VIDA",
    stage_12: "PILAR DEL CIELO",
    stage_13: "SEMILLA ESTELAR",
    stage_14: "ALIENTO UNIVERSO",
    ach_1_title: "Primer Paso",
    ach_1_desc: "Haz clic 1 vez",
    ach_2_title: "Trabajador",
    ach_2_desc: "Haz clic 500 veces",
    ach_3_title: "Automatización",
    ach_3_desc: "Fertilizante Nivel 5",
    ach_4_title: "Rico",
    ach_4_desc: "Consigue 10.000 SP",
    ach_5_title: "Viajero Dim.",
    ach_5_desc: "Llega Dimensión 2",
  },
  // İTALYANCA
  it: {
    settings: "IMPOSTAZIONI",
    achievements: "OBIETTIVI",
    guide: "GUIDA",
    sound_status: "Stato Suono",
    night_day: "NOTTE / GIORNO",
    how_to_play: "COME GIOCARE?",
    reset: "RESETTA",
    start_game: "AVVIA GIOCO",
    username_placeholder: "Il Tuo Nome...",
    guide_text:
      "Clicca sul terreno, coltiva semi. Tieni premuto Spazio per clic rapidi!",
    level_label: "LIVELLO",
    size_label: "Dimen:",
    target_label: "Obiettivo:",
    total_earnings: "GUADAGNI TOTALI",
    total_clicks: "CLIC TOTALI",
    market_title: "MERCATO",
    prestige_title: "PRESTIGIO",
    prestige_desc: "Nuova Dimensione",
    prestige_power: "+50% POTENZA",
    upg_click: "Luce Solare",
    upg_water: "Acqua Viva",
    upg_auto: "Fertilizzante",
    upg_shears: "Potatura",
    upg_gloves: "Guanti",
    upg_med: "Vitamina",
    upg_boost: "Coccinella",
    bonus_click: "+1 Clic",
    bonus_water: "+2 Clic",
    bonus_auto: "+1.0 Auto",
    bonus_shears: "+5.0 Auto",
    bonus_gloves: "+10 Clic",
    bonus_med: "+25.0 Auto",
    bonus_boost: "Vel. x2 (60s)",
    welcome: "Benvenuto",
    good_luck: "Buona Fortuna!",
    insufficient_sp: "SP Insufficienti",
    collect_points: "Raccogli punti.",
    level_up: "DIMENSIONE SU!",
    new_dimension: "Nuova Dimensione:",
    rebirth: "RINASCITA",
    stronger: "Sei più forte!",
    golden_seed: "SEME DORATO",
    bee: "APE",
    offline_earnings: "GUADAGNI OFFLINE",
    stage_0: "SEME",
    stage_1: "PICCOLO GERMOGLIO",
    stage_2: "ALBERELLO",
    stage_3: "GIOVANE ALBERO",
    stage_4: "TRONCO FORTE",
    stage_5: "ALBERO FIORITO",
    stage_6: "ALBERO DA FRUTTO",
    stage_7: "GUARDIANO FORESTA",
    stage_8: "GRANDE PLATANO",
    stage_9: "QUERCIA ANTICA",
    stage_10: "SPIRITO NATURA",
    stage_11: "ALBERO DELLA VITA",
    stage_12: "PILASTRO CIELO",
    stage_13: "SEME STELLARE",
    stage_14: "RESPIRO UNIVERSO",
    ach_1_title: "Primo Passo",
    ach_1_desc: "Clicca 1 volta",
    ach_2_title: "Lavoratore",
    ach_2_desc: "Clicca 500 volte",
    ach_3_title: "Automazione",
    ach_3_desc: "Fertilizzante Liv 5",
    ach_4_title: "Ricco",
    ach_4_desc: "Raccogli 10.000 SP",
    ach_5_title: "Viaggiatore Dim.",
    ach_5_desc: "Raggiungi Dim. 2",
  },
  // ALMANCA
  de: {
    settings: "EINSTELLUNGEN",
    achievements: "ERFOLGE",
    guide: "ANLEITUNG",
    sound_status: "Sound Status",
    night_day: "NACHT / TAG",
    how_to_play: "SPIELANLEITUNG?",
    reset: "ZURÜCKSETZEN",
    start_game: "SPIEL STARTEN",
    username_placeholder: "Namen eingeben...",
    guide_text:
      "Klicke auf den Boden, züchte Samen. Halte die Leertaste gedrückt!",
    level_label: "LEVEL",
    size_label: "Größe:",
    target_label: "Ziel:",
    total_earnings: "GESAMTGEWINN",
    total_clicks: "GESAMT KLICKS",
    market_title: "MARKT",
    prestige_title: "PRESTIGE",
    prestige_desc: "Dimension Hoch",
    prestige_power: "+50% KRAFT",
    upg_click: "Sonnenlicht",
    upg_water: "Lebenswasser",
    upg_auto: "Dünger",
    upg_shears: "Beschneidung",
    upg_gloves: "Handschuhe",
    upg_med: "Vitamin",
    upg_boost: "Marienkäfer",
    bonus_click: "+1 Klick",
    bonus_water: "+2 Klick",
    bonus_auto: "+1.0 Auto",
    bonus_shears: "+5.0 Auto",
    bonus_gloves: "+10 Klick",
    bonus_med: "+25.0 Auto",
    bonus_boost: "Speed x2 (60s)",
    welcome: "Willkommen",
    good_luck: "Viel Glück!",
    insufficient_sp: "Zu wenig SP",
    collect_points: "Sammle Punkte.",
    level_up: "DIMENSION HOCH!",
    new_dimension: "Neue Dimension:",
    rebirth: "WIEDERGEBURT",
    stronger: "Du bist stärker!",
    golden_seed: "GOLDENER SAMEN",
    bee: "BIENE",
    offline_earnings: "OFFLINE-GEWINN",
    stage_0: "SAMEN",
    stage_1: "WINZIGER SPROSS",
    stage_2: "WACHSENDER SETZLING",
    stage_3: "JUNGER BAUM",
    stage_4: "STARKER STAMM",
    stage_5: "BLÜHENDER BAUM",
    stage_6: "OBSTBAUM",
    stage_7: "WALDWÄCHTER",
    stage_8: "GROSSE PLATANE",
    stage_9: "ALTE EICHE",
    stage_10: "NATURGEIST",
    stage_11: "BAUM DES LEBENS",
    stage_12: "HIMMELSSÄULE",
    stage_13: "STERNENSAMEN",
    stage_14: "ATEM DES UNIVERSUMS",
    ach_1_title: "Erster Schritt",
    ach_1_desc: "Klicke 1 mal",
    ach_2_title: "Harter Arbeiter",
    ach_2_desc: "Klicke 500 mal",
    ach_3_title: "Automatisierung",
    ach_3_desc: "Dünger Lvl 5",
    ach_4_title: "Reich",
    ach_4_desc: "Sammle 10.000 SP",
    ach_5_title: "Dimensionsreisender",
    ach_5_desc: "Erreiche Dimension 2",
  },
};

let currentLang = localStorage.getItem("tapSeed_Lang") || "tr";

function t(key) {
  if (!translations[currentLang]) return key;
  return translations[currentLang][key] || key;
}

function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem("tapSeed_Lang", lang);
  updateUITexts();
  if (typeof game !== "undefined" && game.renderPlant) {
    game.renderPlant();
  }
}

function updateUITexts() {
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.getAttribute("data-i18n");
    if (key) {
      if (element.tagName === "INPUT") {
        element.placeholder = t(key);
      } else {
        element.innerText = t(key);
      }
    }
  });
}
